from .scst_loss import ScstRewardCriterion
from .label_smoothed_cross_entropy import AdjustLabelSmoothedCrossEntropyCriterion
from .clip_scst_loss import ClipScstRewardCriterion
from .label_smoothed_encouraging_loss import AdjustLabelSmoothedEncouragingLossCriterion

from .label_smoothed_cross_entropy_for_masked_ofa import AdjustLabelSmoothedCrossEntropyCriterionMaskedOFA

from .seg_criterion import SegCriterion